name: Linters and tests
on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15.5
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - name: Copy envs
        run: cp .env.dist .env
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Test & coverage
        run: npm run coverage
        env:
          CI: true