name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: 'ci: bump version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
